force-app/main/default/objects/Lead/fields/Match_Score__c.field-meta.xml
<CustomField>
    <fullName>Match_Score__c</fullName>
    <description>It indicates similarity score for fuzzy match</description>
    <label>Match Score</label>
    <precision>3</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Matched_Account__c.field-meta.xml
<CustomField>
    <fullName>Matched_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>It stores the matched Account if found.</description>
    <label>Matched Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads</relationshipLabel>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Matched_By__c.field-meta.xml
<CustomField>
    <fullName>Matched_By__c</fullName>
    <description>It shows the source of matching logic.</description>
    <label>Matched By</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domain</fullName>
            </value>
            <value>
                <fullName>Fuzzy</fullName>
            </value>
            <value>
                <fullName>Combined</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/LeadTriggerTest.cls
@isTest
private class LeadTriggerTest {
    @isTest
    static void testLeadTriggerBeforeInsert() {
        Account acc = new Account(Name = 'Trigger Test Account', Website = 'trigger.com');
        insert acc;

        Lead lead = new Lead(LastName = 'Trigger', Company = 'Trigger Test Account', Email = 'trigger@trigger.com');

        Test.startTest();
        insert lead;
        Test.stopTest();

        lead = [SELECT Matched_Account__c, Matched_By__c, Match_Score__c FROM Lead WHERE Id = :lead.Id];

        System.assertEquals('Combined', lead.Matched_By__c);
        System.assertEquals(acc.Id, lead.Matched_Account__c);
        System.assertEquals(1.0, lead.Match_Score__c);
    }
}